### PR TITLE
Enabled git build for m4port , along with patches

### PR DESCRIPTION
**Pull request by HarithaIBM**

### CODE REVIEW

**Review by MikeFultonDev — COMMENTED** [review]
How far does the build get with these changes?

**Comment by HarithaIBM** [comment]
make check went through, with o/p as:

Skipped checks were:
  ./126.changeword ./127.changeword ./128.changeword ./129.changeword ./130.changeword ./131.changeword ./stackovf.test
Failed checks were:
  ./005.command_li:out ./006.command_li:out ./006.command_li:err ./138.include:err

**Comment by HarithaIBM** [comment]
> How far does the build get with these changes?

I see the failures as:
Failed checks were:
  ./005.command_li:out ./006.command_li:out ./006.command_li:err ./138.include:err

**Review by IgorTodorovskiIBM — APPROVED** [review]
LGTM

**Comment by MikeFultonDev** [comment]
Very cool. Can you open up an issue that indicates git build quality and what is failing so we can track what needs to be updated ?

**Review by MikeFultonDev — APPROVED** [review]
looks good!

**Pull request merged**
